name: kidztokenz_app_v2
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  amplify_flutter: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0
  amplify_api: ^1.0.0
  amplify_analytics_pinpoint: ^1.0.0
  font_awesome_flutter: ^9.0.0
  cupertino_icons: ^1.0.0
  flutter_riverpod: ^2.0.0
  riverpod_annotation: ^2.0.0
  go_router: ^13.0.0  

dev_dependencies:
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  custom_lint:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - images/storeicon.png
    - images/m1.png
    - images/m2.png
    - images/m3.png
    - images/m4.png
    - images/m5.png
    - images/m6.png
    - images/m7.png
    - images/m8.png
    - images/m9.png
    - images/m10.png
    - images/m11.png
    - images/facebook-logo.png
    - images/google-logo.png
    - images/amazon-logo.png
    - images/applogo.png  
    - images/badbunny.png
    - images/badelephant.png
    - images/badface.png
    - images/badgiraffe.png
    - images/badleopard.png
    - images/badmonkey.png
    - images/badrocket.png
    - images/badsheep.png
    - images/badstar.png
    - images/badteddybear.png
    - images/badtrain.png
    - images/badtriceratops.png
    - images/bunny.png
    - images/elephant.png
    - images/face.png
    - images/giraffe.png
    - images/leopard.png
    - images/monkey.png
    - images/rocket.png
    - images/sheep.png
    - images/star.png
    - images/teddybear.png
    - images/train.png
    - images/triceratops.png
    - images/tn1.png
    - images/tn2.png
    - images/tn3.png
    - images/tn4.png
    - images/tn5.png
    - images/tn6.png
    - images/tn7.png
    - images/tn8.png
    - images/tn9.png
    - images/tn10.png
    - images/bekind.png
    - images/trophy.png


